### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by deobald** [pariyatti/kosa-clj#29]
- [ ] *.pariyatti.org OAuth?
- [ ] 3rd Party OAuth?
- [ ] ...or local auth?

**Comment by oxalorg** [comment]
Would "HTTP Basic Auth" be enough? We could have an environment variable with a fixed password and just use that to enter the website. :thinking: 

This would be a simple solution, shouldn't take me long to implement it.

**Comment by deobald** [comment]
Yup, that would totally work. For the foreseeable future, there will only be a few users on the website (Brihas, Renate, and maybe Nishant or Steve Hanlon) ... it doesn't seem necessary to add full-blown user accounts until the website and mobile app have seen some use. :)

**Comment by oxalorg** [comment]
Sounds good! I'll add this over the weekends as this is a `v0` milestone and seems super important :)
