### ISSUE TITLE
Kosa: production-readiness

### ISSUE THREAD

**Issue by deobald** [pariyatti/kosa-clj#55]
## Production-Readiness

* [x] add `kosa.pariyatti.app` for production
    * [x] after file permissions change in Ansible, restart the service
    * [x] copy `authorized_keys` from ubuntu user to kosa-user: provision with ubuntu, deploy and seed with kosa-user
    * [x] add a DNS latch script to wait/retry until DNS resolves or fails (for 10 minutes)

**Comment by balwa** [comment]
For DNS latching we can use the Ansible inbuilt task at the beginning of provisioning:

[https://docs.ansible.com/ansible/2.5/modules/wait_for_connection_module.html](https://docs.ansible.com/ansible/2.5/modules/wait_for_connection_module.html)


```
    - name: Wait for newly created system to become reachable
      wait_for_connection:
      
```
