### ISSUE TITLE
Kosa: manual backups

### ISSUE THREAD

**Issue by deobald** [pariyatti/kosa-clj#61]
## Backups

* [x] Enable Automatic Snapshots
* [ ] Once-a-week `rsync` to S3 bucket (bring Kosa down)
    * [x] create bucket in Terraform
    * [x] Python script should notify Discord on Kosa tear-down and restart
    * [ ] Python script should perform sync
    * [ ] Ansible playbook to copy Python script and install / start cron job

**Comment by balwa** [comment]
the versions on prod and sandbox have been updated to enable this, logs can be checked via `zgrep -i cron /var/log/syslog*`
