### ISSUE TITLE
Files written to /tmp directory causing the disk to fill up on server

### ISSUE THREAD

**Issue by balwa** [pariyatti/kosa-clj#70]
Earlier today we received an alert about kosa healthcheck failing (which is a good validation that it is helping us find issues 🎉)

and the status failure was:

```json
{"message":"No space left on device","exception-type":"default","exception":"class java.io.IOException","data":"","stacktrace":["java.base/java.io.FileOutputStream.writeBytes(Native Method)","java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)","java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)","java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)","java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)","kuti.storage.open_uri$copy_uri_stream$fn__19684.invoke(open_uri.clj:22)","kuti.storage.open_uri$copy_uri_stream.invokeStatic(open_uri.clj:22)","kuti.storage.open_uri$copy_uri_stream.invoke(open_uri.clj:21)","kuti.storage.open_uri$download_uri_BANG_.invokeStatic(open_uri.clj:41)","kuti.storage.open_uri$download_uri_BANG_.doInvoke(open_uri.clj:31)","clojure.lang.RestFn.invoke(RestFn.java:410)","kosa.api.status$get$fn__20052.invoke(status.clj:12)","kosa.api.status$get.invokeStatic(status.clj:11)","kosa.api.status$get.invoke(status.clj:9)","kosa.api.handler$status.invokeStatic(handler.clj:14)","kosa.api.handler$status.invoke(handler.clj:13)","kosa.middleware.auth$basic_auth_middleware$fn__33493.invoke(auth.clj:63)","buddy.auth.middleware$wrap_authorization$fn__33457.invoke(middleware.clj:114)","buddy.auth.middleware$wrap_authentication$fn__33450.invoke(middleware.clj:60)","ring.logger$wrap_log_response$fn__34261.invoke(logger.clj:121)","ring.logger$wrap_log_request_params$fn__34251.invoke(logger.clj:60)","ring.middleware.flash$wrap_flash$fn__33521.invoke(flash.clj:39)","ring.middleware.session$wrap_session$fn__33960.invoke(session.clj:108)","kosa.middleware.params$wrap_path_params$fn__34413.invoke(params.clj:23)","ring.middleware.keyword_params$wrap_keyword_params$fn__34323.invoke(keyword_params.clj:53)","reitit.ring.middleware.exception$wrap$fn__34452$fn__34453.invoke(exception.clj:49)","muuntaja.middleware$wrap_format$fn__34728.invoke(middleware.clj:73)","ring.middleware.multipart_params$wrap_multipart_params$fn__34405.invoke(multipart_params.clj:171)","ring.middleware.params$wrap_params$fn__34682.invoke(params.clj:75)","ring.middleware.json$wrap_json_body$fn__34142.invoke(json.clj:60)","ring.middleware.json$wrap_json_params$fn__34158.invoke(json.clj:102)","ring.middleware.json$wrap_json_response$fn__34193.invoke(json.clj:143)","ring.logger$wrap_log_request_start$fn__34256.invoke(logger.clj:88)","reitit.ring$ring_handler$fn__23611.invoke(ring.cljc:329)","kosa.middleware.fake_http_verb$wrap_http_verb_method$fn__34882.invoke(fake_http_verb.clj:21)","ring.middleware.multipart_params$wrap_multipart_params$fn__34405.invoke(multipart_params.clj:171)","ring.middleware.params$wrap_params$fn__34682.invoke(params.clj:75)","clojure.lang.AFn.applyToHelper(AFn.java:154)","clojure.lang.AFn.applyTo(AFn.java:144)","clojure.lang.AFunction$1.doInvoke(AFunction.java:31)","clojure.lang.RestFn.invoke(RestFn.java:408)","clojure.lang.Var.invoke(Var.java:384)","ring.adapter.jetty$proxy_handler$fn__34976.invoke(jetty.clj:27)","ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)","org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)","org.eclipse.jetty.server.Server.handle(Server.java:516)","org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)","org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)","org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)","org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)","org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)","org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)","org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)","org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)","org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)","org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)","org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)","org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)","org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)","org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)","java.base/java.lang.Thread.run(Thread.java:833)"],"uri":"/status"}
``` 
The server showed that the root partition was full:
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        78G   78G     0 100% /
```
Inspecting the filesystem, /tmp director was consuming most of the storage. Looking at the files there, it looks like we are generating about 12 temporary files a minute at the moment.
<img width="865" alt="Screen Shot 2022-07-11 at 7 32 47 AM" src="https://user-images.githubusercontent.com/4284516/178175732-28f05ae7-25cb-4a8c-ab1f-d098e0f7571d.png">

A server reboot will clear the tmp directory, though it doesn't get rebooted that often. Another workaround (that was applied right now) is to clean tmp directory files based on creation time:

`find /tmp -ctime +4 -exec rm -rf {} +`

```
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        78G   48G   31G  62% /
```

**Comment by deobald** [comment]
Hooray for monitoring! It would seem the process which downloads the original MP3s from pariyatti.org is aggressively repeating itself ... though these all should have been downloaded when the server was initially constructed. I'm a bit confused as to why Kosa's downloading the same file over and over again. So there are two problems:

1. The unnecessary repetition
2. The lack of clean-up in `/tmp` after a file is downloaded

**Comment by oxalorg** [comment]
Looks like once we actually save the file outside of `tmp` we should also delete the temp file `(.delete tempFile)` (unless it's being reused elsewhere? unlikely though)

https://github.com/pariyatti/kosa/blob/33d2b73f720c5290f3288ec18fa79a1ac5c0caf2/src/kuti/storage/core.clj#L58-L64 

The `renameTo` is commented out probably because it does not have good cross compatibility, we could either use `java.nio...Files` api or just delete the tmp file afterwords.

EDIT: My kosa setup isn't working locally atm, I'll get it up and running and see if I can test this out locally. If I can I'll send a PR

**Comment by deobald** [comment]
@oxalorg Indeed, I remember doing this "fix". ;) It should definitely be deleted after the copy.

However, that doesn't explain why Kosa is attempting to download attachments 5 times a minute ... that shouldn't be happening for attachments which have already been downloaded. Deleting the temp file cures the symptom but I'd also like to get rid of the disease as part of this card. :)

**Comment by balwa** [comment]
I think i have a hint, why, it's the health check that is generating one file each time it runs and from the route 53 health check dashboard we are seeing 6 checkers running at a rate of 30 seconds, which means 12 checks per minute
<img width="421" alt="Screen Shot 2022-07-16 at 7 49 27 PM" src="https://user-images.githubusercontent.com/4284516/179358783-a0149d2d-e0e4-4e02-a279-27808ac29b91.png">

My hint was the health check output
```
"pariyatti-status":{"test-url":"http://download.pariyatti.org/dohas/001_Doha.mp3","test-file":{"tempfile":"/tmp/kuti-download-398952075314981456.mp3","filename":"001_Doha.mp3","content-type":"audio/mpeg","size":544475},"pariyatti-ok":true}}
```

**Comment by deobald** [comment]
@oxalorg I've fixed the major issue in this commit: https://github.com/pariyatti/kosa/commit/b40f313720b57d65be005a531557e8cbfd01775e

...however, I'm not going to bother with the storage cleanup right now. I've forked this issue: https://github.com/pariyatti/kosa/issues/74 The fix should be similar, but it's in the infrastructure code and pays to be thoroughly tested. If you're keen to submit a PR, please do! 🙏
